# Development Dockerfile
FROM oven/bun:1.1.34-alpine

WORKDIR /app

RUN apk add --no-cache python3 make g++

# Copy package files
COPY package.json bun.lock ./

# Install dependencies
RUN bun install --no-save --frozen-lockfile

# Expose port
EXPOSE 3000

# Start the application in development mode
CMD ["bun", "run", "dev"]
